### PR TITLE
#108: nemobot reminds to rebase when github is checking mergeability (closes #108)

### LINKED ISSUE #108: nemobot reminds to rebase when github is checking mergeability
## description
https://github.com/buildo/elephant/pull/27#issuecomment-240126948

http://stackoverflow.com/questions/30619549/why-does-github-api-return-an-unknown-mergeable-state-in-a-pull-request

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
sends reminder only if `pull.mergeable === false`

## misc
this happens only if author assigns PR while GitHub is still checking PR mergeability

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #108

### tests performed
use fake webhook payloads to test:
- mergeable: null
  - reminder delayed of 5 seconds
- mergeable: false
  - reminder sent immediately
- updatedPR.mergeable !== true
  - comment posted

**NB: if after 5 seconds GitHub is still checking mergeability we ignore the webhook** (as `pull.mergeable` will not be `true`)
This is OK in my opinion as 5 seconds should be more than enough for GitHub

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@gabro in the elephant PR (https://github.com/buildo/elephant/pull/27) GitHub sent only one `synchronize` event with `mergeable: null`.

With this fix we'll remove false positives in favor of possible false negatives... (what if that PR was actually not mergeable? GitHub doesn't send any event after the first one apparently)

**Comment by gabro** [comment]
maybe it sends one if the PR becomes non-mergeable?

**Comment by FrancescoCioria** [comment]
@gabro updated PR with workaround (and added test plan)

**Comment by gabro** [comment]
👍

**Pull request merged**
